### ISSUE TITLE
JWT Sign and Verify updates

### ISSUE THREAD

**Issue by nitro-neal** [TBD54566975/web5-kt#190] opened 2024-01-17 20:53 UTC
A few thoughts and updates need to be made to our JWT signing logic:

``` Sign ```
    // TODO: ensure that publicKeyJwk is not null
    // TODO: figure out how to make more reliable since algorithm is technically not a required property of a JWK
    verificationMethodId and jwt.header.keyID  could be different: for example we may have a key id as a JWK thumbprint but a verification method ID as did:example:abcd#key-1

``` Verify ```
 Could make a presentation definition where I'm specifically requesting expired credentials. this check would fail, since JWT validation fails if the exp property is in the past

More reference here - https://github.com/TBD54566975/web5-kt/pull/184

**Comment by nitro-neal** [comment] 2024-03-21 17:30
The only open question now is this:

// TODO: figure out how to make more reliable since algorithm is technically not a required property of a JWK

@jiyoontbd is this going to be irrelevant soon? Is jwt signing / verifying changing?

**Comment by jiyoontbd** [comment] 2024-03-22 07:18
@nitro-neal yea, i think so. #262 introduces our own jws + jwt types, and also removes `jwtutil` altogether, where that todo was recorded.

closing as duplicate of #234 - let me know if you disagree and we can reopen!

**Closed by jiyoontbd** 2024-03-22 07:18 UTC
Labels: bug
