### ISSUE TITLE
API leak on com.danubetech:verifiable-credentials-java

### ISSUE THREAD

**Issue by ALRubinger** [TBD54566975/web5-kt#228] opened 2024-02-12 06:51 UTC
Submodule `credentials` in `web5-kt` is exporting an `api` dependency:

*  `api(libs.comDanubetechVerifiableCredentials)` > `com.danubetech:verifiable-credentials-java`

This means consumers are expected to use this dep directly. Encapsulate necessary operations in the `web5-kt` API such that we're not exposing the `com.danubetech` APIs and asking users to rely on those. Our use internally should be an impl detail. Then move this to an `implementation` dependency.

**Comment by jiyoontbd** [comment] 2024-03-12 06:14
closing as duplicate of #188

**Closed by jiyoontbd** 2024-03-12 06:14 UTC
Labels: enhancement, good first issue
